/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Generator.java
 *
 * Created on 2011-09-15, 10:58:30
 */
package graphfinder2.gui;

import graphfinder2.executor.Supervisor;
import graphfinder2.typedGraph.Degrees;
import graphfinder2.typedGraph.TypedGraphCreator;
import graphfinder2.typedGraph.TypedGraphCreators;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.DefaultComboBoxModel;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author damian
 */
public class GeneratorPanel extends javax.swing.JPanel {

	private final Timer timer = new Timer();
	private TimerTask timerTask = null;

	/** Creates new form Generator */
	public GeneratorPanel() {
		initComponents();
		fillStageComboBox();
		fillTypeComboBox();
		enableAll(true);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        stageComboBox = new javax.swing.JComboBox();
        typeComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        fromSpinner = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        toSpinner = new javax.swing.JSpinner();
        startButton = new javax.swing.JButton();
        optimalizeCheckBox = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        progressProgressBar = new javax.swing.JProgressBar();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Parameters"));

        jLabel1.setText("Degree");

        jLabel2.setText("Type");

        stageComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stageComboBoxActionPerformed(evt);
            }
        });

        typeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("From");

        fromSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(6), Integer.valueOf(2), null, Integer.valueOf(1)));
        fromSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                fromSpinnerStateChanged(evt);
            }
        });

        jLabel4.setText("To");

        toSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1000), Integer.valueOf(2), null, Integer.valueOf(1)));
        toSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                toSpinnerStateChanged(evt);
            }
        });

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        optimalizeCheckBox.setSelected(true);
        optimalizeCheckBox.setText("Optimalize");
        optimalizeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optimalizeCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stageComboBox, 0, 307, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(typeComboBox, 0, 307, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(fromSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(toSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(optimalizeCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                        .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {fromSpinner, toSpinner});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(stageComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fromSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(toSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optimalizeCheckBox)
                    .addComponent(startButton))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Progress"));

        progressProgressBar.setStringPainted(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(progressProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(progressProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

	private void stageComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stageComboBoxActionPerformed
		fillTypeComboBox();
	}//GEN-LAST:event_stageComboBoxActionPerformed

	private void typeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeComboBoxActionPerformed
		// brak akcji
	}//GEN-LAST:event_typeComboBoxActionPerformed

	private void fromSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_fromSpinnerStateChanged
		((SpinnerNumberModel) toSpinner.getModel()).setMinimum((Integer) fromSpinner.getModel().getValue());
	}//GEN-LAST:event_fromSpinnerStateChanged

	private void toSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_toSpinnerStateChanged
		// brak akcji
	}//GEN-LAST:event_toSpinnerStateChanged

	private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
		// rozpoczecie przetwarzania
		generate();
	}//GEN-LAST:event_startButtonActionPerformed

	private void optimalizeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optimalizeCheckBoxActionPerformed
		// brak akcji
	}//GEN-LAST:event_optimalizeCheckBoxActionPerformed

	/**
	 * Uzupelna stopnie grafu
	 */
	private void fillStageComboBox() {
		DefaultComboBoxModel dcbm = new DefaultComboBoxModel();
		dcbm.addElement("ALL");
		for (Degrees stage : Degrees.values()) {
			dcbm.addElement(stage.name());
		}
		dcbm.setSelectedItem("ALL");
		stageComboBox.setModel(dcbm);
	}

	/**
	 * Uzupelnia typy
	 */
	private void fillTypeComboBox() {
		DefaultComboBoxModel dcbm = new DefaultComboBoxModel();
		// jesli wszystkie
		if (((String) stageComboBox.getModel().getSelectedItem()).equals("ALL")) {
			for (TypedGraphCreators creator : TypedGraphCreators.values()) {
				dcbm.addElement(creator.name());
			}
		} else {
			Degrees stage = Degrees.valueOf((String) stageComboBox.getModel().getSelectedItem());
			for (TypedGraphCreators creator : TypedGraphCreators.values()) {
				if (creator.getStage().equals(stage)) {
					dcbm.addElement(creator.name());
				}
			}
		}
		typeComboBox.setModel(dcbm);
	}

	/**
	 * Uruchamia lub wyszarza gui
	 * @param state
	 */
	private void enableAll(boolean state) {
		stageComboBox.setEnabled(state);
		typeComboBox.setEnabled(state);
		fromSpinner.setEnabled(state);
		toSpinner.setEnabled(state);
		optimalizeCheckBox.setEnabled(state);
		startButton.setEnabled(state);
	}

	private void generate() {
		// blokowanie gui
		enableAll(false);
		// wyluskiwanie typu
		final TypedGraphCreator creator = TypedGraphCreators.valueOf((String) typeComboBox.getModel().getSelectedItem()).getCreator();
		// tworzenie nadzorcy
		final int from = (Integer) fromSpinner.getModel().getValue();
		final int to = (Integer) toSpinner.getModel().getValue();
		final Supervisor supervisor = new Supervisor(creator, from, to, optimalizeCheckBox.isSelected());
		// jesli nie ma zadan
		if (supervisor.getTotalTaskNumber() == 0) {
			enableAll(true);
			return;
		}

		// tworzenie zadania dla tmera
		timerTask = new TimerTask() {

			public void run() {
				java.awt.EventQueue.invokeLater(new Runnable() {

					public void run() {
						// jesli koniec
						if (supervisor.isFinished()) {
							// przywracamy gui
							progressProgressBar.getModel().setValue(100);
							enableAll(true);
							timerTask.cancel();
							timerTask = null;
						} else {
							int progress = (supervisor.getSolvedTaskCounter() * 100) / supervisor.getTotalTaskNumber();
							progressProgressBar.getModel().setValue(progress);
						}
					}
				});
			}
		};
		timer.schedule(timerTask, 100, 100);
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner fromSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JCheckBox optimalizeCheckBox;
    private javax.swing.JProgressBar progressProgressBar;
    private javax.swing.JComboBox stageComboBox;
    private javax.swing.JButton startButton;
    private javax.swing.JSpinner toSpinner;
    private javax.swing.JComboBox typeComboBox;
    // End of variables declaration//GEN-END:variables
}
