/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Generator.java
 *
 * Created on 2011-09-15, 08:51:01
 */
package graphfinder2.gui;

import graphfinder2.graph.Graph;
import graphfinder2.typedGraph.Degrees;
import graphfinder2.typedGraph.TypedGraph;
import graphfinder2.typedGraph.TypedGraphCreator;
import graphfinder2.typedGraph.TypedGraphCreators;
import java.io.IOException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author damian
 */
public class ShowerPanel extends javax.swing.JPanel {

	private Graph currentGraph = null;
	private boolean doubleRing = false;

	/** Creates new form Generator */
	public ShowerPanel() {
		initComponents();
		fillStageComboBox();
		fillTypeComboBox();
		enableParams();
		buildGraph();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        stageComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        typeComboBox = new javax.swing.JComboBox();
        p0Label = new javax.swing.JLabel();
        p0Spinner = new javax.swing.JSpinner();
        p1Label = new javax.swing.JLabel();
        p1Spinner = new javax.swing.JSpinner();
        p2Label = new javax.swing.JLabel();
        p2Spinner = new javax.swing.JSpinner();
        p3Label = new javax.swing.JLabel();
        p3Spinner = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        nodeNumberSpinner = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        graphTextArea = new javax.swing.JTextArea();
        showButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Parameters"));

        jLabel1.setText("Degree");

        stageComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stageComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Type");

        typeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeComboBoxActionPerformed(evt);
            }
        });

        p0Label.setText("P0");

        p0Spinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        p0Spinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                p0SpinnerStateChanged(evt);
            }
        });

        p1Label.setText("P1");

        p1Spinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        p1Spinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                p1SpinnerStateChanged(evt);
            }
        });

        p2Label.setText("P2");

        p2Spinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                p2SpinnerStateChanged(evt);
            }
        });

        p3Label.setText("P3");

        p3Spinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                p3SpinnerStateChanged(evt);
            }
        });

        jLabel7.setText("Node number");

        nodeNumberSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(16), Integer.valueOf(2), null, Integer.valueOf(1)));
        nodeNumberSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                nodeNumberSpinnerStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nodeNumberSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(p0Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p0Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(p1Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p1Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(p2Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p2Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(p3Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p3Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stageComboBox, 0, 311, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(typeComboBox, 0, 311, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {nodeNumberSpinner, p0Spinner, p1Spinner, p2Spinner, p3Spinner});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {p0Label, p1Label, p2Label, p3Label});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(stageComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(nodeNumberSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p0Label)
                    .addComponent(p0Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p1Label)
                    .addComponent(p1Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p2Label)
                    .addComponent(p2Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p3Label)
                    .addComponent(p3Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Graph"));

        graphTextArea.setColumns(20);
        graphTextArea.setRows(5);
        jScrollPane1.setViewportView(graphTextArea);

        showButton.setText("Show image");
        showButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save image");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addComponent(saveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(showButton)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {saveButton, showButton});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showButton)
                    .addComponent(saveButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

	private void stageComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stageComboBoxActionPerformed
		fillTypeComboBox();
		enableParams();
		buildGraph();
	}//GEN-LAST:event_stageComboBoxActionPerformed

	private void typeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeComboBoxActionPerformed
		enableParams();
		buildGraph();
	}//GEN-LAST:event_typeComboBoxActionPerformed

	private void nodeNumberSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_nodeNumberSpinnerStateChanged
		buildGraph();
	}//GEN-LAST:event_nodeNumberSpinnerStateChanged

	private void p0SpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_p0SpinnerStateChanged
		buildGraph();
	}//GEN-LAST:event_p0SpinnerStateChanged

	private void p1SpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_p1SpinnerStateChanged
		buildGraph();
	}//GEN-LAST:event_p1SpinnerStateChanged

	private void p2SpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_p2SpinnerStateChanged
		buildGraph();
	}//GEN-LAST:event_p2SpinnerStateChanged

	private void p3SpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_p3SpinnerStateChanged
		buildGraph();
	}//GEN-LAST:event_p3SpinnerStateChanged

	private void showButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showButtonActionPerformed
		if (currentGraph != null) {
			JDialog dialog = new JDialog();
			dialog.setModal(true);
			dialog.add(new JLabel((new GraphBufferedImage(currentGraph, doubleRing)).getImageIcon()));
			dialog.pack();
			dialog.setVisible(true);
		}
	}//GEN-LAST:event_showButtonActionPerformed

	private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
		// zapis obrazka
		try {
			(new GraphBufferedImage(currentGraph, doubleRing)).save("graphview.png");
		} catch (IOException ex) {
			JOptionPane.showMessageDialog(this, "File writing error: " + ex, "ERROR", JOptionPane.ERROR_MESSAGE);
		}
	}//GEN-LAST:event_saveButtonActionPerformed

	/**
	 * Uzupelna stopnie grafu
	 */
	private void fillStageComboBox() {
		DefaultComboBoxModel dcbm = new DefaultComboBoxModel();
		dcbm.addElement("ALL");
		for (Degrees stage : Degrees.values()) {
			dcbm.addElement(stage.name());
		}
		dcbm.setSelectedItem("ALL");
		stageComboBox.setModel(dcbm);
	}

	/**
	 * Uzupelnia typy
	 */
	private void fillTypeComboBox() {
		DefaultComboBoxModel dcbm = new DefaultComboBoxModel();
		// jesli wszystkie
		if (((String) stageComboBox.getModel().getSelectedItem()).equals("ALL")) {
			for (TypedGraphCreators creator : TypedGraphCreators.values()) {
				dcbm.addElement(creator.name());
			}
		} else {
			Degrees stage = Degrees.valueOf((String) stageComboBox.getModel().getSelectedItem());
			for (TypedGraphCreators creator : TypedGraphCreators.values()) {
				if (creator.getStage().equals(stage)) {
					dcbm.addElement(creator.name());
				}
			}
		}
		typeComboBox.setModel(dcbm);
	}

	/**
	 * Uruchamia parametry
	 */
	private void enableParams() {
		TypedGraphCreator creator = TypedGraphCreators.valueOf((String) typeComboBox.getModel().getSelectedItem()).getCreator();
		int paramsNumber = creator.getRequiredParamsNumber();

		p0Spinner.setEnabled(false);
		p1Spinner.setEnabled(false);
		p2Spinner.setEnabled(false);
		p3Spinner.setEnabled(false);
		p0Label.setEnabled(false);
		p1Label.setEnabled(false);
		p2Label.setEnabled(false);
		p3Label.setEnabled(false);

		switch (paramsNumber) {
			case 4:
				p3Spinner.setEnabled(true);
				p3Label.setEnabled(true);
			case 3:
				p2Spinner.setEnabled(true);
				p2Label.setEnabled(true);
			case 2:
				p1Spinner.setEnabled(true);
				p1Label.setEnabled(true);
			case 1:
				p0Spinner.setEnabled(true);
				p0Label.setEnabled(true);
		}
	}

	/**
	 * Metoda wywolywana do budowania grafu
	 */
	private void buildGraph() {

		try {
			// proba wyluskania kreatora
			TypedGraphCreator creator = TypedGraphCreators.valueOf((String) typeComboBox.getModel().getSelectedItem()).getCreator();
			String text = "Graph type: " + creator.getTypeName() + "\n";

			// ilosc wezlow
			int nodeNumber = (Integer) nodeNumberSpinner.getModel().getValue();
			if (!creator.isValidNodeNumber(nodeNumber)) {
				graphTextArea.setText("Incorrect node number");

				// zapis aktualnego grafu
				currentGraph = null;
				showButton.setEnabled(false);
				saveButton.setEnabled(false);
				return;
			}
			text += "Node number: " + nodeNumber + "\n";

			// parametry
			int[] params = new int[4];
			params[0] = (Integer) p0Spinner.getModel().getValue();
			params[1] = (Integer) p1Spinner.getModel().getValue();
			params[2] = (Integer) p2Spinner.getModel().getValue();
			params[3] = (Integer) p3Spinner.getModel().getValue();
			if (!creator.isValidParams(nodeNumber, params)) {
				graphTextArea.setText("Incorrect parameters");

				// zapis aktualnego grafu
				currentGraph = null;
				showButton.setEnabled(false);
				saveButton.setEnabled(false);
				return;
			}
			text += "Parameters: " + Arrays.toString(params) + "\n";

			// budowanie grafu
			TypedGraph typedGraph = creator.create(nodeNumber, params);
			// wyznaczanie wynikow
			text += "Average length path: " + typedGraph.getAverage() + "\n";
			text += "Maximum diameter: " + typedGraph.getDiameter() + "\n";
			text += "" + typedGraph.getResultPreamble() + "\n";
			text += "" + typedGraph.getResultLine() + "\n";
			// budowa grafu
			text += "Graph build: \n";
			text += typedGraph.getGraph().toString();

			graphTextArea.setText(text);

			// zapis aktualnego grafu
			currentGraph = typedGraph.getGraph();
			doubleRing = creator.getTypeName().matches(".*NDR.*");
			showButton.setEnabled(true);
			saveButton.setEnabled(true);
		} catch (IllegalArgumentException e) {
			// nie ma takiego enuma
			graphTextArea.setText("Chose graph type");
			// zapis aktualnego grafu
			currentGraph = null;
			showButton.setEnabled(false);
			saveButton.setEnabled(false);
		} catch (Exception e) {
			// nieprzewidziana sytuacja
			graphTextArea.setText("Unexpected error: " + e.getMessage());
			// zapis aktualnego grafu
			currentGraph = null;
			showButton.setEnabled(false);
			saveButton.setEnabled(false);
		}
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea graphTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner nodeNumberSpinner;
    private javax.swing.JLabel p0Label;
    private javax.swing.JSpinner p0Spinner;
    private javax.swing.JLabel p1Label;
    private javax.swing.JSpinner p1Spinner;
    private javax.swing.JLabel p2Label;
    private javax.swing.JSpinner p2Spinner;
    private javax.swing.JLabel p3Label;
    private javax.swing.JSpinner p3Spinner;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton showButton;
    private javax.swing.JComboBox stageComboBox;
    private javax.swing.JComboBox typeComboBox;
    // End of variables declaration//GEN-END:variables
}
